### ISSUE TITLE
DateTime関連のリファクタ

### ISSUE THREAD

**Issue by loxygenK** [isso0424/gakkouike#21]
`DateTime#toIso8601String()` を知っていましたか? 少なくとも僕は知りませんでした

**Comment by loxygenK** [comment]
`dt-refactor`ブランチでやります
ちなみにこれによって1つファイルが消えますやったね

**Comment by isso0424** [comment]
知ってたけど面倒でした(言い訳)

**Comment by loxygenK** [comment]
これやったらデータの構造が変わっちゃうので大惨事ですね
どうすればいいですか()

**Comment by isso0424** [comment]
おぉん
具体的にどうなるん？

**Comment by loxygenK** [comment]
保存形式が`[{year: n, month: m, day: o}, ...]`だったのが`["yyyy/MM/dd", "yyyy/MM/dd" ... }`になります

**Comment by isso0424** [comment]
ん？
ああsubject型のread/writeが全書き換えになるのか()

**Comment by isso0424** [comment]
つよくいきて

**Comment by loxygenK** [comment]
はい(ぴえん)
