### ISSUE TITLE
大変恐縮ですが初期設定画面のUIをもうちょい変えたく存じます

### ISSUE THREAD

**Issue by loxygenK** [isso0424/gakkouike#30]
恐れ入りますが`init-conf_ui`ブランチにて操作させていただきたいと存じあげる所存であると考えております。今後とも宜しくお願いいたします。

**Comment by loxygenK** [comment]
↑Q. 何重敬語だこれ　わからん

**Comment by isso0424** [comment]
深夜テンションで動けばいいやで作ったからね、ｼｶﾀﾅｲﾈ

**Comment by loxygenK** [comment]
深夜テンションUIは維持しますよ

**Comment by isso0424** [comment]
草
