### ISSUE TITLE
deploygate使う

### ISSUE THREAD

**Issue by isso0424** [isso0424/gakkouike#33]

**Comment by isso0424** [comment]
https://dply.me/m7j5v9
ここのリンクからダウンロードできるはず

**Comment by isso0424** [comment]
ちなみにデバッグの手段としては俺しか使えないと思う
理由としては無料プランで使えるのが個人開発プランしか無い

**Comment by isso0424** [comment]
1アカウントしか紐付けできない+5バージョンしかとっておけない
=>公開の手段
としたいんだがどうだ
ちなみにiOS版もいける

**Comment by loxygenK** [comment]
†グループ機能†はだめですか

**Comment by isso0424** [comment]
あるんですか(初耳)

**Comment by loxygenK** [comment]
あるらしい
俺がなんとかする

**Comment by isso0424** [comment]
天才じゃんでもちょいまち

**Comment by isso0424** [comment]
一回こっちでやっちゃったやつどうする?
git reset しとく?

**Comment by loxygenK** [comment]
今どうなってますか…
ブランチ切ってある? or masterにズドン？

**Comment by isso0424** [comment]
commitしてない

**Comment by loxygenK** [comment]
ん〜〜〜わからんなぁ()
deploygateのuser名教えろ！！！！！！！！！！！！！！！！よ！！！！！！！！！！！！！！

**Comment by isso0424** [comment]
isso0424

**Comment by loxygenK** [comment]
こるくのuser名教えろ！！！！！！！！！！！！！！（無理難題）

**Comment by isso0424** [comment]
しらん()

**Comment by isso0424** [comment]
で、いけそう?

**Comment by loxygenK** [comment]
多分行ける

**Comment by isso0424** [comment]
天才かよ

**Comment by isso0424** [comment]
じゃあreset --soft HEADしとくわ

**Comment by loxygenK** [comment]
こるくにDMで聞き出そうとしたらTwitterの通知切っちゃっててさぁ…
LINEで聞くわ(粘着)

**Comment by isso0424** [comment]
草

**Comment by loxygenK** [comment]
![image](https://user-images.githubusercontent.com/55672846/75652333-26935780-5c9e-11ea-881b-93b77a9711b3.png)
対戦ありがとうございました

**Comment by isso0424** [comment]
しってた

**Comment by isso0424** [comment]
https://qiita.com/ishihamat/items/a897754eed6b5c1ec6ed
頑張ってこの辺つかってiOS公開してください

**Comment by loxygenK** [comment]
がんばる

**Comment by loxygenK** [comment]
閉じんの忘れてたゾ()
