### ISSUE TITLE
Configの終業日指定でガバる

### ISSUE THREAD

**Issue by loxygenK** [isso0424/gakkouike#43]
初期設定の終業日が`2100/08/10`なのに、
https://github.com/brokenManager/gakkouike/blob/a0c82e13e3ed5d0aa87350791926fa5e1c5a2d38/lib/config/config.dart#L324
だと怒られちゃうゾ

**Comment by isso0424** [comment]
あっすまん何も考えてなかった（）

**Comment by loxygenK** [comment]
樋口一葉
自分がAssignされてるやつそろそろ終わるので僕やっちゃおうか?

**Comment by loxygenK** [comment]
勝手に手が動いてやってました
