### ISSUE TITLE
警告ラインが留年ラインを下回って設定されているときの挙動

### ISSUE THREAD

**Issue by Colk-tech** [isso0424/gakkouike#50]
現状では警告ラインが留年ラインを下回って設定されている場合、欠課時数が留年ラインに到達するまでなにも教えてもらえなくなてっています()
もしユーザーが間違って警告ラインを留年ラインより下回って設定している場合、留年が確定するまで警告をもらえないので非常に危険です。
警告ラインが留年ラインを下回って設定されたとき、エラーメッセージを表示させてほしいです。

**Comment by isso0424** [comment]
頑張って♡

**Comment by loxygenK** [comment]
ん〜こるく氏やろうね

**Comment by Colk-tech** [comment]
無慈悲なassigned

**Comment by isso0424** [comment]
しろってloxyが...

**Comment by loxygenK** [comment]
Assignは草

**Comment by Colk-tech** [comment]
ちなみにこれは私が間違ってやりました
「始業前に終業する特殊な学校には対応していません」応用すれば簡単に実装できそうですね(小並感)

**Comment by isso0424** [comment]
じゃあ頑張って

**Comment by loxygenK** [comment]
がんばれ

**Comment by Colk-tech** [comment]
ブランチ behavior_fix_at_#50 で作業するかも知れません
