### ISSUE TITLE
あと何回休んでもいいのかの実装

### ISSUE THREAD

**Issue by Colk-tech** [isso0424/gakkouike#51]
「警告ライン達成まで あと n 時間 です」
「留年ライン達成まで あと n 時間 です」

**Comment by loxygenK** [comment]
達成(celebration)で草
こるく氏やりますか

**Comment by Colk-tech** [comment]
達成(celebration)

**Comment by Colk-tech** [comment]
コード読んで実装してみる
できそうになかったらHelp wantedつけますんで()

**Comment by loxygenK** [comment]
了解したゾ＾〜

**Comment by loxygenK** [comment]
UFI violationしてて草
