### ISSUE TITLE
[警告|留年] ラインの範囲制限

### ISSUE THREAD

**Issue by loxygenK** [isso0424/gakkouike#53]
0〜1に制限しようね
あと0〜100のほうが優しいと思うんだけど @isso0424  はどう思う?

**Comment by isso0424** [comment]
0 ~ 100でいいんじゃね(めんどいから0~1)にした

**Comment by loxygenK** [comment]
じゃあ一緒に100までにしちゃうか
`line-limit` で操作しますわよ！

**Comment by isso0424** [comment]
がんばえ
