### ISSUE TITLE
カレンダーの挙動を変える

### ISSUE THREAD

**Issue by isso0424** [isso0424/gakkouike#54]
流石にAlertDialogはダサいのでカレンダーの下に一覧を表示するようにする

**Comment by isso0424** [comment]
そのうちやる

**Comment by isso0424** [comment]
カレンダーの下に欠課リストだそうと思ったら死んだ
Dareka Yatte Clemens @loxygenK @Colk-tech @ko50

**Comment by loxygenK** [comment]
おれやるかも
